const translations = {
    fr: {
        beautyTreatments: "Beauty treatments",
        appointment: "Appointment",
        allAppointment: "All appointment",
        confirmed: "Appointment confirmed",
        discount: "Discount offer",
        duration: "Durée",
        price: "Prix",
        cancel: "Cancel Appointment if you want",
        pending: "Pending Confirmation",
        changePicture: "change your picture",
        deletePicture: "Delete your picture",
        changeName: "change your name",
        changePassword: "change your password",
        changeLanguage: "change language",
        changeEmail: "change your email/phone",
        yourName: "votre nom",
    },
    en: {
        beautyTreatments: "Beauty treatments",
        appointment: "Appointment",
        allAppointment: "All appointment",
        confirmed: "Appointment confirmed",
        discount: "Discount offer",
        duration: "Duration",
        price: "Price",
        cancel: "Cancel Appointment if you want",
        pending: "Pending Confirmation",
        changePicture: "change your picture",
        deletePicture: "Delete your picture",
        changeName: "change your name",
        changePassword: "change your password",
        changeLanguage: "change language",
        changeEmail: "change your email/phone",
        yourName: "your name",
    },
    ar: {
        beautyTreatments: "علاجات التجميل",
        appointment: "الموعد",
        allAppointment: "كل المواعيد",
        confirmed: "المواعيد المؤكدة",
        discount: "عرض الخصم",
        duration: "المدة",
        price: "السعر",
        cancel: "إلغاء الموعد إذا أردت",
        pending: "بانتظار التأكيد",
        changePicture: "غيّر صورتك",
        deletePicture: "احذف صورتك",
        changeName: "غيّر اسمك",
        changePassword: "غيّر كلمة المرور",
        changeLanguage: "غيّر اللغة",
        changeEmail: "غيّر بريدك/هاتفك",
        yourName: "اسمك",
    }
};

export default translations;